---
# See also: roles/workstation/defaults/main/packages.yml

# Nested list of Gnome packages:
gnome_packages:
  - "{{ [
      'gnome-shell-extension-apps-menu',
      'gnome-shell-extension-places-menu',
      'gnome-shell-extension-user-theme',
    ]
    if (ansible_facts.os_family == 'RedHat') else [] }}"
  - "{{ [
      'gnome-extensions-app',
      'gnome-shell-extension-blur-my-shell',
    ]
    if (ansible_facts.distribution == 'Fedora') else [] }}"
  - "{{ [
      'gnome-shell-extension-prefs',
      'gnome-shell-extensions',
    ]
    if (ansible_facts.os_family == 'Debian') else [] }}"
  - "{{ [
      'ptyxis',
    ]
    if (gnome_terminal_is_ptyxis)
    else [
      'gnome-terminal',
      'gnome-terminal-nautilus' if (ansible_facts.os_family == 'RedHat')
      else 'nautilus-extension-gnome-terminal',
    ] }}"
  - dconf-editor
  - gnome-control-center
  - gnome-screenshot
  - gnome-shell
  - gnome-shell-extension-appindicator
  - gnome-text-editor
  - gnome-tweaks
  - seahorse
  - xdg-desktop-portal-gnome

# Packages to remove from Gnome workstations (Fedora/Debian/Ubuntu):
gnome_blacklisted_packages:
  # Fedora 39+ / Gnome 45+
  - "{{ [
      'eog',
      'fedora-chromium-config',
      'fedora-chromium-config-gnome',
      'fedora-chromium-config-gssapi',
    ]
    if (ansible_facts.distribution == 'Fedora') else [] }}"
  - "{{ [
      'gnome-terminal',
      'gnome-terminal-nautilus' if (ansible_facts.os_family == 'RedHat')
      else 'nautilus-extension-gnome-terminal',
    ]
    if (gnome_terminal_is_ptyxis) else [] }}"
  # Unwanted common Gnome packages
  - chrome-gnome-shell
  - gedit
  - gedit-common
  - gnome-boxes
  - gnome-browser-connector
  - gnome-connections
  - gnome-contacts
  - gnome-documents
  - gnome-maps
  - gnome-music
  - gnome-photos
  - gnome-shell-extension-desktop-icons-ng
  - gnome-todo
  - gnome-tour
  - rhythmbox
  - seahorse-nautilus  # (deprecated)
  - shotwell
  - shotwell-common
  - tilix  # (obsolete)
  - totem
  - totem-common
  - vinagre
  # Pre-installed games (Debian)
  - aisleriot
  - atomix
  - five-or-more
  - four-in-a-row
  - gnome-2048
  - gnome-chess
  - gnome-games
  - gnome-klotski
  - gnome-mahjongg
  - gnome-mines
  - gnome-nibbles
  - gnome-robots
  - gnome-sudoku
  - gnome-taquin
  - gnome-tetravex
  - hitori
  - iagno
  - lightsoff
  - quadrapassel
  - swell-foop
  - tali
