---
# Accepted states to update pip packages:
python_pip_update_states:
  - present
  - latest

# Update arguments for ansible.builtin.pip:
python_pip_update_args:
  state: latest

# Accepted states to update pipx packages:
python_pipx_update_states:
  - present  # install
  - latest   # install + upgrade
  - install
  - upgrade

# Update arguments for community.general.pipx:
python_pipx_update_args:
  state: upgrade
  include_injected: true
