---
# include_role: name=oszi.general.podman tasks_from=deploy

- name: Deploy podman networks
  containers.podman.podman_network:
  args: "{{ item }}"
  with_items: "{{ podman_networks_list | oszi.utils.unique_nested_list('name') }}"

- name: Deploy podman images
  containers.podman.podman_image:
  args: "{{ item }}"
  with_items: "{{ podman_images_list | oszi.utils.unique_nested_list('name') }}"

- name: Deploy podman containers
  containers.podman.podman_container:
  args: "{{ item }}"
  with_items: "{{ podman_containers_list | oszi.utils.unique_nested_list('name') }}"

- name: Deploy podman pods
  containers.podman.podman_pod:
  args: "{{ item }}"
  with_items: "{{ podman_pods_list | oszi.utils.unique_nested_list('name') }}"
