---
- name: Deploy podman networks
  containers.podman.podman_network:
  args: "{{ {'name': item.key} | combine(item.value) }}"
  with_dict: "{{ podman_networks }}"

- name: Deploy podman images
  containers.podman.podman_image:
  args: "{{ item }}"
  with_items: "{{ podman_images }}"

- name: Deploy podman containers
  containers.podman.podman_container:
  args: "{{ {'name': item.key} | combine(item.value) }}"
  with_dict: "{{ podman_containers }}"

- name: Deploy podman pods
  containers.podman.podman_pod:
  args: "{{ {'name': item.key} | combine(item.value) }}"
  with_dict: "{{ podman_pods }}"
