---
- name: Ensure podman-docker is present or absent
  ansible.builtin.package:
    name: "podman-docker"
    state: "{{ podman_docker_enabled | ternary('present', 'absent') }}"

# XXX: Introduced in podman 5.0
- name: Check upstream /etc/profile.d/podman-docker.sh
  ansible.builtin.stat:
    path: "/etc/profile.d/podman-docker.sh"
  register: _podman_docker_etc_profile_result

- name: Enable podman daemons and docker-compose
  when: podman_docker_enabled
  block:
    - name: Enable system podman.socket
      ansible.builtin.systemd:
        name: "podman.socket"
        scope: "system"
        enabled: true

    - name: Enable user podman.socket
      ansible.builtin.systemd:
        name: "podman.socket"
        scope: "global"
        enabled: true

    - name: Set DOCKER_HOST if upstream had not done so already
      when: not _podman_docker_etc_profile_result.stat.exists
      ansible.builtin.copy:
        content: |
          if [ -z "${DOCKER_HOST:-}" ]; then
            export DOCKER_HOST="unix://${XDG_RUNTIME_DIR:-/run}/podman/podman.sock"
          fi
        dest: "/etc/profile.d/podman-docker-socket.sh"
        mode: "0644"

    - name: Ensure docker-compose is present or absent
      ansible.builtin.package:
        name: "docker-compose"
        state: "{{ podman_docker_compose_enabled | ternary('present', 'absent') }}"

- name: Remove obsolete /etc/profile.d/podman-docker-socket.sh?
  when: not podman_docker_enabled or _podman_docker_etc_profile_result.stat.exists
  ansible.builtin.file:
    path: "/etc/profile.d/podman-docker-socket.sh"
    state: "absent"
