---
galaxy_info:
  description: "Utility role for fact gathering."
  author: "David O. (oszi.dev)"
  license: "BSD-3-Clause"
  min_ansible_version: "2.18.0"

  platforms:
    - name: Fedora
      versions: [all]
    - name: EL
      versions: [all]
    - name: Debian
      versions: [all]
    - name: Ubuntu
      versions: [all]
    - name: macOS
      versions: [all]

  galaxy_tags:
    - utils
    - rootless
    - baselinux
