---
# List of explicit gather subsets for ansible.builtin.setup:
# Implies !all and !min unless explicitly specified.
facts_subset:
  - "min"
  - "virtual"

# Optional facts filter to pass to ansible.builtin.setup:
# Avoid if possible, complicates caching and role dependency deduplication.
facts_filter: []

# Path for ansible_local facts.
# Empty means omit, default is /etc/ansible/facts.d
facts_path: ""

# Default timeout in seconds for individual fact gathering.
facts_timeout: 10
