---
# Prefix for custom keyboard shortcuts - the root key contains the list of subkeys.
gnome_users_dconf_custom_keybindings_prefix: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings"

# Default Gnome Screenshots and Screencasts paths relative to $HOME.
# * Tasks from gnome-user.yml are run as gnome_users_item!
gnome_users_xdg_pictures_screenshots_path: "{{ gnome_users_info.home }}/Pictures/Screenshots"
gnome_users_xdg_videos_screencasts_path: "{{ gnome_users_info.home }}/Videos/Screencasts"

# Relative to HOME. Always use the default XDG_CONFIG_HOME.
gnome_users_xdg_config_directory: ".config"

# Placeholder values for loop variables to pass argument specs validation.
# Loop vars will take precedence over this.
gnome_users_item: "placeholder"
gnome_users_info:
  name: "placeholder"
  home: "placeholder"
  password: "placeholder"
  shell: "placeholder"
  system: false
  uid: 0
  group: 0
  groups: []
