---
# Prefix for custom keyboard shortcuts - the root key contains the list of subkeys.
gnome_users_dconf_custom_keybindings_prefix: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings"

# Dconf path and prefix for the default profile of Ptyxis:
gnome_users_dconf_ptyxis_terminal_default_profile_path: "/org/gnome/Ptyxis/default-profile-uuid"
gnome_users_dconf_ptyxis_terminal_profiles_prefix: "/org/gnome/Ptyxis/Profiles/"

# Dconf path and prefix for the default profile of legacy Gnome-Terminal:
# * dconf read .../profiles:/default returns nothing if default.
gnome_users_dconf_legacy_terminal_default_profile_gsettings_schema: "org.gnome.Terminal.ProfilesList default"
gnome_users_dconf_legacy_terminal_profiles_prefix: "/org/gnome/terminal/legacy/profiles:/:"

# Default Gnome Screenshots and Screencasts paths relative to $HOME.
# * Tasks from gnome-user.yml are run as gnome_users_item!
gnome_users_xdg_pictures_screenshots_path: "{{ gnome_users_info.home }}/Pictures/Screenshots"
gnome_users_xdg_videos_screencasts_path: "{{ gnome_users_info.home }}/Videos/Screencasts"

# Relative to HOME. Always use the default XDG_CONFIG_HOME.
gnome_users_xdg_config_directory: ".config"

# Placeholders for loop and task variables to pass argument_specs validation.
# Wrapping loop_var prevents "loop variable is already in use" warnings.
# Task variables take precedence over vars/main.
gnome_users_item: "{{ _gnome_users_item_var | default('__PLACEHOLDER__') }}"
gnome_users_info:
  name: "__PLACEHOLDER__"
  comment: "__PLACEHOLDER__"
  home: "__PLACEHOLDER__"
  password: "__PLACEHOLDER__"
  shell: "__PLACEHOLDER__"
  system: false
  uid: 0
  group: 0
  groups: []
  changed: false
