---
# Systemd template unit of the upstream podman-kube service
podman_kube_template_service: "podman-kube@.service"

# Base path to install PodSpec files to - overridable with absolute paths
podman_kube_pods_base_path: "/etc/containers/kube"
