---
_containers_etc_path: "/opt/containers/etc"
_containers_var_path: "/opt/containers/var"

_containers_subnet: "172.17.0.0/24"
_containers_ip_range: "172.17.0.240/28"
_containers_gateway: "{{ _containers_subnet | ansible.utils.ipaddr('1') }}"

podman_networks:
  vmbridge-containers:
    driver: "macvlan"
    gateway: "{{ _containers_gateway }}"
    subnet: "{{ _containers_subnet }}"
    ip_range: "{{ _containers_ip_range }}"
    ipv6: false
    opt:
      parent: "enp1s0"
      mode: "bridge"

podman_config_containers: |
  # Ansible managed
  # See /usr/share/containers/containers.conf
  [containers]
  dns_servers = ["{{ _containers_gateway }}"]
  dns_searches = ["."]
  log_driver = "journald"
  label = true
  default_sysctls = [
    "net.ipv4.ping_group_range=0 0",
    "net.ipv6.conf.all.disable_ipv6=1",
    "net.ipv6.conf.default.disable_ipv6=1",
  ]

_certbot_uid0: 130000

_container_certbot_cli_ini: |
  agree-tos
  non-interactive
  email admin@example.com
  dns-cloudflare
  dns-cloudflare-credentials /etc/letsencrypt/cloudflare.ini

_container_certbot_cloudflare_ini: |
  dns_cloudflare_api_token = "{{ cloudflare_dns_api_token }}"

_container_firewall_lockdown_script_template: |
  #!/bin/bash
  ## Run with {{ containerhost_toolbox_container_image }}
  set -euo pipefail
  echo "iptables-nft-restore..." >&2
  cat << IP4EOF | iptables-nft-restore
  *filter
  :INPUT ACCEPT [0:0]
  -A INPUT -m conntrack --ctstate INVALID -j DROP
  :FORWARD DROP [0:0]
  -A FORWARD -m conntrack --ctstate INVALID -j DROP
  -A FORWARD -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
  :OUTPUT ACCEPT [0:0]
  -A OUTPUT -m conntrack --ctstate INVALID -j DROP
  -A OUTPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
  -A OUTPUT -o lo -j ACCEPT
  -A OUTPUT -p udp -m udp -d {{ _containers_gateway }}/32 --dport 53 -j ACCEPT
  -A OUTPUT -p tcp -m tcp -d {{ _containers_gateway }}/32 --dport 53 -j ACCEPT
  -A OUTPUT -d {{ _containers_ip_range }} -j ACCEPT
  -A OUTPUT -d 10.0.0.0/8 -j REJECT --reject-with icmp-port-unreachable
  -A OUTPUT -d 172.16.0.0/12 -j REJECT --reject-with icmp-port-unreachable
  -A OUTPUT -d 192.168.0.0/16 -j REJECT --reject-with icmp-port-unreachable
  -A OUTPUT -d 100.64.0.0/10 -j REJECT --reject-with icmp-port-unreachable
  -A OUTPUT -d 224.0.0.0/4 -j DROP
  -A OUTPUT -d 255.255.255.255/32 -j DROP
  COMMIT
  IP4EOF
