---
argument_specs:
  main:
    short_description: Assertions utility role
    description:
      - Validates requirements with assertion rules
      - Use as role dependencies to take advantage of dependency deduplication
    author:
      - "David O. (oszi.dev)"
    options: &options
      assert_that:
        description:
          - List of assertion rules for M(ansible.builtin.assert) to validate requirements
          - Should contain literal strings without interpolation
        type: list
        elements: str
        required: true

      assert_task_msg:
        description:
          - Customized message used for task names
        type: str
        required: false
        default: "Assert requirements"

      assert_fail_msg:
        description:
          - Customized message used for failing assertions
        type: str
        required: false

      assert_success_msg:
        description:
          - Customized message used for successful assertions
        type: str
        required: false

  assert:
    short_description: Direct entrypoint for assertions
    description:
      - Does not apply `always` or any other tag, unlike entrypoint `main`
    options:
      <<: *options
