---
# WARNING: The inventory must be designed for rootless mode!
- name: Deploy all rootless roles
  hosts: "{{ rootless_hosts | default('rootless') }}"
  become: false
  gather_facts: false
  roles:
    - oszi.general.bootstrap
    - oszi.general.python
    - oszi.general.shell
    - oszi.general.dotfiles
    - oszi.general.cloudflare_dns
    - oszi.general.acme
    - oszi.general.podman_kube
    - oszi.general.podman_quadlets
    - oszi.general.flatpak
    - oszi.general.gnome_users
