---
# WARNING: The inventory must be designed for rootless mode!
- name: Run rootless roles from dotfiles to containers
  hosts: "{{ rootless_hosts | default('rootless') }}"
  become: false
  gather_facts: false
  roles:
    - oszi.general.bootstrap
    - oszi.general.dotfiles
    - oszi.general.acme
    - oszi.general.podman_kube
    - oszi.general.podman_quadlets
    - oszi.general.flatpak
