---
# List of podman-kube pods as dictionaries.
# See the argument spec for detailed documentation.
podman_kube_list: "{{ {} | oszi.general.update_nested_dict(podman_kube_pods, 'pod_spec')
  | oszi.general.update_nested_dict(podman_kube_copy_files, 'files')
  | oszi.general.update_nested_dict(podman_kube_init_scripts, 'init_script')
  | oszi.general.update_nested_dict(podman_kube_post_install_scripts, 'post_install_script')
  | oszi.general.nested_dict_to_list('path') }}"

# XXX: Deprecated, backwards-compatible variables.
podman_kube_pods: {}
podman_kube_copy_files: {}
podman_kube_init_scripts: {}
podman_kube_post_install_scripts: {}
