---
# Disable Snap?
snap_disabled: "{{ ansible_facts.os_family != 'Debian' and snap_packages | length == 0 }}"

# List of dicts of snaps to install:
# - {name: "aws-cli", channel: "v1/stable", classic: true}
snap_packages: []

# List of snaps to always remove:
snap_blacklisted_packages: []
