---
galaxy_info:
  description: "Deploy Kubernetes-spec services with podman-kube@.service"
  author: "David O. (oszi.dev)"
  license: "BSD-3-Clause"
  min_ansible_version: "2.18.0"

  platforms:
    - name: Fedora
      versions: [all]
    - name: EL
      versions: [all]
    - name: Debian
      versions: [all]
    - name: Ubuntu
      versions: [all]

  galaxy_tags:
    - general
    - rootless
    - linux
    - containers
