---
- name: Facts tasks
  tags: [always]
  block:
    - name: Import facts tasks
      ansible.builtin.import_tasks:
        file: facts.yml

    - name: Facts role completed
      ansible.builtin.debug:
        msg: prevent-multiple-inclusions
      no_log: true
