---
- name: Workstation role tasks
  tags: [workstation]
  block:
    - name: Workstation package setup tasks
      ansible.builtin.import_tasks:
        file: packages.yml

    - name: Workstation system tasks
      ansible.builtin.import_tasks:
        file: system.yml
