---
- name: Set podman-kube pod loop vars
  ansible.builtin.set_fact:
    _podman_kube_pod_path: "{{ [podman_kube_pods_base_path, podman_kube_pod_item.key] | path_join }}"
    _podman_kube_copy_results: null  # Reset previous iteration.

- name: Copy static files for the kube
  when: podman_kube_pod_item.key in podman_kube_copy_files
  block:
    # Do not set permissions as they could be changed by the service.
    - name: "Ensure directories exist for podman-kube pod {{ podman_kube_pod_item.key }}"
      ansible.builtin.file:  # noqa: risky-file-permissions
        path: "{{ item }}"
        state: "directory"
      with_items: "{{ podman_kube_copy_files[podman_kube_pod_item.key]
        | map(attribute='dest') | map('dirname') | unique }}"

    - name: "Copy static files for podman-kube pod {{ podman_kube_pod_item.key }}"
      ansible.builtin.copy:
        dest: "{{ item.dest }}"
        content: "{{ item.content | default(omit) }}"
        src: "{{ item.src | default(omit) }}"
        owner: "{{ item.owner | default(omit) }}"
        group: "{{ item.group | default(item.owner | default(omit)) }}"
        mode: "{{ item.mode | default(omit) }}"
      with_items: "{{ podman_kube_copy_files[podman_kube_pod_item.key] }}"
      register: _podman_kube_copy_results

- name: "Run init script for podman-kube pod {{ podman_kube_pod_item.key }}"
  when: podman_kube_pod_item.key in podman_kube_init_scripts
  ansible.builtin.shell: |
    set -euxo pipefail
    {{ podman_kube_init_scripts[podman_kube_pod_item.key] }}
  args:
    # White lie to only execute once before installing.
    creates: "{{ _podman_kube_pod_path }}"
    executable: "/bin/bash"

- name: "Ensure directory for podman-kube PodSpec {{ podman_kube_pod_item.key }}"
  ansible.builtin.file:
    path: "{{ _podman_kube_pod_path | dirname }}"
    state: "directory"
    # owner: ansible_user or root
    mode: "0755"

- name: "Install podman-kube PodSpec {{ podman_kube_pod_item.key }}"
  ansible.builtin.copy:
    content: "{{ podman_kube_pod_item.value }}"
    dest: "{{ _podman_kube_pod_path }}"
    # owner: ansible_user or root
    mode: "0644"
  register: _podman_kube_pod_result

- name: "Restart podman-kube pod {{ podman_kube_pod_item.key }}"
  ansible.builtin.systemd:
    name: "{{ lookup('oszi.general.systemd_escape', _podman_kube_pod_path, template=podman_kube_template_service) }}"
    scope: "{{ podman_kube_systemd_scope }}"
    daemon_reload: "{{ _podman_kube_changed }}"
    state: "{{ 'restarted' if _podman_kube_changed else 'started' }}"
    enabled: true
  vars:
    _podman_kube_changed: "{{ _podman_kube_pod_result.changed
      or _podman_kube_copy_results is not none and _podman_kube_copy_results.changed }}"

- name: "Run post-install script for podman-kube pod {{ podman_kube_pod_item.key }}"
  when: _podman_kube_pod_result.changed and podman_kube_pod_item.key in podman_kube_post_install_scripts
  ansible.builtin.shell: |
    set -euxo pipefail
    {{ podman_kube_post_install_scripts[podman_kube_pod_item.key] }}
  args:
    executable: "/bin/bash"
  changed_when: true
