---
# Keep in mind that the dconf CLI tool, which this module wraps around, utilizes an unusual syntax
# for the values (GVariant). For example, if you wanted to provide a string value, the correct syntax
# would be value="'myvalue'" - with single quotes as part of the Ansible parameter value.

# When using loops in combination with a value like [('xkb', 'us'), ('xkb', 'hu')],
# you need to be aware of possible type conversions. Applying a filter "{{ item.value | string }}"
# to the parameter variable can avoid potential conversion problems.

# Friendly format for setting custom keyboard shortcuts:
# List of dicts with binding, command and name attributes in GVariant string format.
# Do NOT set custom keybindings in gnome_users_dconf_vars!
gnome_users_dconf_custom_keybindings: []

# Ptyxis default profile dconf settings (if it exists):
gnome_users_dconf_ptyxis_terminal_default_profile_vars: {}
# Legacy Gnome-Terminal default profile dconf settings (if it exists):
gnome_users_dconf_legacy_terminal_default_profile_vars: {}

# Use the gnome_users_item loop var for varying multi-user configurations...
# With lookup tables: /org/gnome/...: "{{ user_dconf_vars[gnome_users_item]['/org/gnome/...'] }}"
# or with jinja conditionals.

# Dict of dconf settings. Set to override my personal defaults below...
# Or combine them: {{ gnome_users_dconf_vars_default | combine(gnome_users_dconf_vars_extra) }}
gnome_users_dconf_vars: "{{ gnome_users_dconf_vars_default }}"
gnome_users_dconf_vars_default:
  # Apple Magick KB: Emulate PrintScrn, Numpad with dot, lv3:ralt_alt (Shift+R_Alt) is patched as Compose Key.
  /org/gnome/desktop/input-sources/xkb-options: ['apple:alupckeys', 'kpdl:dotoss', 'lv3:ralt_alt']
  /org/gnome/desktop/input-sources/sources: "[('xkb', 'us'), ('xkb', 'hu')]"

  /org/gnome/desktop/wm/keybindings/switch-input-source: ['<Control><Shift>Space']
  /org/gnome/desktop/wm/keybindings/switch-input-source-backward: "@as []"
  /org/gnome/desktop/wm/keybindings/switch-applications: ['<Super>Tab']
  /org/gnome/desktop/wm/keybindings/switch-applications-backward: ['<Shift><Super>Tab']
  /org/gnome/desktop/wm/keybindings/switch-group: ['<Super>Above_Tab']
  /org/gnome/desktop/wm/keybindings/switch-group-backward: ['<Shift><Super>Above_Tab']
  /org/gnome/desktop/wm/keybindings/switch-windows: ['<Alt>Tab']
  /org/gnome/desktop/wm/keybindings/switch-windows-backward: ['<Shift><Alt>Tab']

  /org/gnome/desktop/wm/keybindings/switch-to-workspace-left: ['<Super>Left']
  /org/gnome/desktop/wm/keybindings/switch-to-workspace-right: ['<Super>Right']
  /org/gnome/desktop/wm/keybindings/switch-to-workspace-1: ['<Super>Home']
  /org/gnome/desktop/wm/keybindings/switch-to-workspace-last: ['<Super>End']

  /org/gnome/desktop/wm/keybindings/maximize: ['<Super>Up', '<Shift><Super>Up']
  /org/gnome/desktop/wm/keybindings/minimize: ['<Super>Down']
  /org/gnome/desktop/wm/keybindings/unmaximize: ['<Shift><Super>Down']
  /org/gnome/mutter/keybindings/toggle-tiled-left: ['<Shift><Super>Left']
  /org/gnome/mutter/keybindings/toggle-tiled-right: ['<Shift><Super>Right']

  /org/gnome/desktop/wm/keybindings/move-to-corner-ne: ['<Shift><Super>Page_Up']
  /org/gnome/desktop/wm/keybindings/move-to-corner-nw: ['<Shift><Super>Home']
  /org/gnome/desktop/wm/keybindings/move-to-corner-se: ['<Shift><Super>Page_Down']
  /org/gnome/desktop/wm/keybindings/move-to-corner-sw: ['<Shift><Super>End']

  /org/gnome/desktop/wm/keybindings/move-to-monitor-down: ['<Control><Shift><Super>Down']
  /org/gnome/desktop/wm/keybindings/move-to-monitor-up: ['<Control><Shift><Super>Up']
  /org/gnome/desktop/wm/keybindings/move-to-monitor-left: ['<Control><Shift><Super>Left']
  /org/gnome/desktop/wm/keybindings/move-to-monitor-right: ['<Control><Shift><Super>Right']

  /org/gnome/desktop/wm/keybindings/move-to-workspace-left: ['<Control><Super>Left']
  /org/gnome/desktop/wm/keybindings/move-to-workspace-right: ['<Control><Super>Right']

  /org/gnome/desktop/wm/keybindings/always-on-top: ['<Control><Super>Up']
  /org/gnome/desktop/wm/keybindings/lower: ['<Control><Super>Down']

  /org/gnome/shell/keybindings/toggle-message-tray: ['<Alt><Super>Tab']
  /org/gnome/shell/keybindings/toggle-application-view: ['LaunchB']
  /org/gnome/shell/keybindings/toggle-overview: ['LaunchA']

  /org/gnome/shell/keybindings/show-screenshot-ui: ['Print']
  /org/gnome/shell/keybindings/show-screen-recording-ui: ['<Super>Print']  # Instead of: <Shift><Control><Alt>R
  /org/gnome/shell/keybindings/screenshot: ['<Shift>Print']
  /org/gnome/shell/keybindings/screenshot-window: ['<Control>Print']  # Incompatible default: <Alt>Print

  /org/gnome/settings-daemon/plugins/media-keys/screensaver: ['<Super>Delete', '<Super>L']

  /org/gnome/desktop/session/idle-delay: "uint32 {{ 1800 if ansible_facts.virtualization_role != 'guest' else 0 }}"

  /org/gnome/desktop/wm/preferences/action-middle-click-titlebar: "'lower'"
  /org/gnome/desktop/wm/preferences/button-layout: "':minimize,close'"
  /org/gnome/desktop/wm/preferences/theme: "'Adwaita'"

  /org/gnome/desktop/interface/gtk-theme: "'{{ 'Yaru-dark' if ansible_facts.distribution == 'Ubuntu' else 'Adwaita' }}'"
  /org/gnome/desktop/interface/icon-theme: "'{{ 'Yaru' if ansible_facts.distribution == 'Ubuntu' else 'Adwaita' }}'"
  /org/gnome/shell/extensions/user-theme/name: "'transparent'"

  /org/gnome/desktop/calendar/show-weekdate: "true"
  /org/gnome/desktop/interface/clock-format: "'24h'"
  /org/gnome/desktop/interface/clock-show-date: "true"
  /org/gnome/desktop/interface/clock-show-seconds: "true"
  /org/gnome/desktop/interface/clock-show-weekday: "true"
  /org/gnome/desktop/interface/color-scheme: "'prefer-dark'"
  /org/gnome/desktop/interface/document-font-name: "'Liberation Serif 11'"
  /org/gnome/desktop/interface/enable-hot-corners: "true"
  /org/gnome/desktop/interface/font-aliasing: "'rgba'"
  /org/gnome/desktop/interface/font-hinting: "'slight'"
  /org/gnome/desktop/interface/font-name: "'Cantarell 11'"
  /org/gnome/desktop/interface/monospace-font-name: "'Liberation Mono 11'"
  /org/gnome/desktop/interface/show-battery-percentage: "true"
  /org/gnome/desktop/interface/text-scaling-factor: "1.0"
  /org/gnome/desktop/interface/toolkit-accessibility: "false"
  /org/gnome/desktop/sound/allow-volume-above-100-percent: "true"

  /org/gnome/mutter/attach-modal-dialogs: "false"
  /org/gnome/mutter/dynamic-workspaces: "true"
  /org/gnome/mutter/workspaces-only-on-primary: "true"

  /org/gnome/nautilus/list-view/default-visible-columns: ['name', 'size', 'date_modified']
  /org/gnome/nautilus/list-view/use-tree-view: "true"
  /org/gnome/nautilus/preferences/default-folder-viewer: "'list-view'"
  /org/gnome/nautilus/preferences/fts-enabled: "false"
  /org/gnome/nautilus/preferences/show-create-link: "true"
  /org/gnome/nautilus/preferences/show-delete-permanently: "true"
  /org/gnome/nautilus/preferences/sort-directories-first: "true"

  /org/gnome/desktop/privacy/old-files-age: "uint32 30"
  /org/gnome/desktop/privacy/recent-files-max-age: "30"
  /org/gnome/desktop/privacy/remember-recent-files: "true"
  /org/gnome/desktop/privacy/remove-old-temp-files: "true"
  /org/gnome/desktop/privacy/remove-old-trash-files: "true"
  /org/gnome/desktop/privacy/report-technical-problems: "false"
  /org/gnome/desktop/privacy/send-software-usage-stats: "false"
  /org/gnome/desktop/privacy/usb-protection-level: "'lockscreen'"
  /org/gnome/desktop/privacy/usb-protection: "true"

  # Restrict dangerous Tracker Miner and thumbnails!
  /org/freedesktop/tracker/miner/files/enable-monitors: "{{ (ansible_facts.virtualization_role == 'guest') | lower }}"
  /org/freedesktop/tracker/miner/files/index-removable-devices: "false"
  /org/freedesktop/tracker/miner/files/index-recursive-directories: "@as []"
  /org/freedesktop/tracker/miner/files/index-single-directories: "@as []"
  /org/gnome/desktop/search-providers/disable-external: "true"
  /org/gnome/desktop/thumbnailers/disable-all: "{{ (ansible_facts.virtualization_role != 'guest') | lower }}"

  /org/gnome/desktop/media-handling/autorun-x-content-ignore: "@as []"
  /org/gnome/desktop/media-handling/autorun-x-content-open-folder: "@as []"
  /org/gnome/desktop/media-handling/autorun-x-content-start-app: "@as []"

  /org/gnome/settings-daemon/plugins/power/idle-dim: "false"
  /org/gnome/settings-daemon/plugins/power/power-button-action: "'nothing'"
  /org/gnome/settings-daemon/plugins/power/sleep-inactive-ac-type: "'nothing'"
  /org/gnome/settings-daemon/plugins/power/sleep-inactive-battery-type: "'nothing'"

  /org/gnome/settings-daemon/plugins/media-keys/next: ['AudioNext']
  /org/gnome/settings-daemon/plugins/media-keys/play: ['AudioPlay']
  /org/gnome/settings-daemon/plugins/media-keys/previous: ['AudioPrev']
  /org/gnome/settings-daemon/plugins/media-keys/volume-down: ['AudioLowerVolume']
  /org/gnome/settings-daemon/plugins/media-keys/volume-mute: ['AudioMute']
  /org/gnome/settings-daemon/plugins/media-keys/volume-up: ['AudioRaiseVolume']

  # Disabled keybindings / shortcut conflicts.
  /org/gnome/desktop/wm/keybindings/move-to-center: "@as []"
  /org/gnome/desktop/wm/keybindings/move-to-side-e: "@as []"
  /org/gnome/desktop/wm/keybindings/move-to-side-n: "@as []"
  /org/gnome/desktop/wm/keybindings/move-to-side-s: "@as []"
  /org/gnome/desktop/wm/keybindings/move-to-side-w: "@as []"
  /org/gnome/desktop/wm/keybindings/move-to-workspace-1: "@as []"
  /org/gnome/desktop/wm/keybindings/move-to-workspace-last: "@as []"
  /org/gnome/desktop/wm/keybindings/show-desktop: "@as []"
  /org/gnome/mutter/keybindings/switch-monitor: ['XF86Display']
  /org/gnome/settings-daemon/plugins/media-keys/rotate-video-lock-static: "@as []"
  /org/gnome/settings-daemon/plugins/media-keys/screencast: "@as []"
  /org/gnome/settings-daemon/plugins/media-keys/screenreader: "@as []"
  /org/gnome/shell/keybindings/focus-active-notification: "@as []"
  /org/gnome/shell/keybindings/shift-overview-down: "@as []"
  /org/gnome/shell/keybindings/shift-overview-up: "@as []"

  # Gnome-Text-Editor settings
  /org/gnome/TextEditor/discover-settings: "true"  # .editorconfig
  /org/gnome/TextEditor/highlight-current-line: "true"
  /org/gnome/TextEditor/indent-style: "'space'"
  /org/gnome/TextEditor/indent-width: "-1"  # -1 = tab-width
  /org/gnome/TextEditor/tab-width: "uint32 4"
  /org/gnome/TextEditor/show-line-numbers: "true"
  /org/gnome/TextEditor/show-map: "true"
