---
# List of users to use as become_user to configure Gnome (become if gnome_users_item != ansible_user):
# noqa: var-naming[no-role-prefix]
gnome_users: "{{ [ansible_user] if ansible_user | default('root') != 'root'
  and 'workstations' in group_names else [] }}"

# Role-local template vars:
# {{ gnome_users_item }} - Loop var of gnome_users.
# {{ gnome_users_info }} - Result of ansible.builtin.user for gnome_users_item.

# Override Gnome Screenshots and Screencasts directories by symlinking
# gnome_users_screenshots_path to gnome_users_xdg_pictures_screenshots_path ($XDG_PICTURES_DIR)
# and to gnome_users_xdg_videos_screencasts_path ($XDG_VIDEOS_DIR).
gnome_users_screenshots_path: ""
