---
galaxy_info:
  description: "Manage python packages from the distribution, and with pip or pipx"
  author: "David O. (oszi.dev)"
  license: "BSD-3-Clause"
  min_ansible_version: "2.18.0"

  platforms:
    - name: Fedora
      versions: [all]
    - name: EL
      versions: [all]
    - name: Debian
      versions: [all]
    - name: Ubuntu
      versions: [all]

  galaxy_tags:
    - general
    - linux
    - baselinux
    - rootless
