---
galaxy_info:
  description: "Linux workstation setup with Gnome Shell."
  author: "David O. (oszi.dev)"
  license: "BSD-3-Clause"
  min_ansible_version: "2.18.0"

  platforms:
    - name: Fedora
      versions: [all]
    - name: Debian
      versions: [all]
    - name: Ubuntu
      versions: [all]

  galaxy_tags:
    - environments
    - linux
    - workstation

dependencies:
  - role: oszi.environments.baselinux
  - role: oszi.general.libvirt
  - role: oszi.general.flatpak
  - role: oszi.general.snap
  - role: oszi.general.chromium_policies
  - role: oszi.general.gnome
  - role: oszi.general.gnome_users
